language: php

php: [7.1, 7.2, 7.3]

branches:
  except:
    - /^bugfix\/.*$/
    - /^feature\/.*$/
    - /^optimization\/.*$/

before_script:
  - composer install --prefer-source --no-interaction --no-progress
  - export PATH=./bin:$PATH

script:
  -  php vendor/bin/phpspec run
  -  php vendor/bin/behat